Training:
  epochs: 30
  learning_rate: 0.00001

Data:
  train_data_path: "E:/Diploma/FraudDetection/train.csv"
  val_data_path: "E:/Diploma/FraudDetection/val.csv"

device: 'cpu'
imsize: 320
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
batch_size: 32
shuffle: True
num_workers: 8
weights: 'MobileNet_V2_Weights.DEFAULT'
autocast_enabled: True
#MobileNet_V2_Weights.DEFAULT
#EfficientNet_B0_Weights.DEFAULT