FROM python:3.11-slim-buster

RUN useradd --create-home --home-dir /app --shell /bin/bash app
WORKDIR /app

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY requirements ./requirements
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements/dev.txt

COPY . .
USER app
