Training:
  epochs: 1
  learning_rate: 0.0001

Data:
  train_data_path: "E:/kbtu_courses/diploma_project/src/diploma/models/liveness/model_training/csv_data/train_v2_upd.csv"
  val_data_path: "E:/kbtu_courses/diploma_project/src/diploma/models/liveness/model_training/csv_data/val_v2_upd.csv"

device: 'cuda'
imsize: 300
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
batch_size: 32
shuffle: True
num_workers: 8
weights: 'EfficientNet_B1_Weights.DEFAULT'
autocast_enabled: True
#MobileNet_V2_Weights.DEFAULT
#EfficientNet_B0_Weights.DEFAULT
